!ArenaConfig
arenas:
  arenas:
    0: !Arena
      blackouts: []
      items:
      - !Item
        colors:
        - !RGB
          b: 153
          g: 153
          r: 153
        - !RGB
          b: 153
          g: 153
          r: 153
        name: Wall
        positions:
        - !Vector3
          x: 1
          y: 2
          z: 3
        - !Vector3
          x: 1
          y: 2
          z: 3
        rotations:
        - 1
        - 2
        sizes:
        - !Vector3
          x: 1
          y: 2
          z: 3
        - !Vector3
          x: 1
          y: 2
          z: 3
      - !Item
        colors:
        - !RGB
          b: 153
          g: 153
          r: 153
        - !RGB
          b: 153
          g: 153
          r: 153
        name: Wall
        positions:
        - !Vector3
          x: 1
          y: 2
          z: 3
        - !Vector3
          x: 1
          y: 2
          z: 3
        rotations:
        - 1
        - 2
        sizes:
        - !Vector3
          x: 1
          y: 2
          z: 3
        - !Vector3
          x: 1
          y: 2
          z: 3
      t: 250
