!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 30
        y: 0
        z: 4
      rotations: []
      sizes: []
    - !Item
      colors: []
      name: GoodGoal
      positions:
      - !Vector3
        x: 30
        y: 0
        z: 4
      rotations: []
      sizes: []
    t: 250
