!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 10
        y: 0
        z: 13
      rotations: []
      sizes: []
    - !Item
      colors: []
      name: GoodGoal
      positions:
      - !Vector3
        x: 10
        y: 0
        z: 13
      rotations: []
      sizes: []
    t: 250
