!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnel
      positions:
      - !Vector3
        x: 3
        y: 0
        z: 19
      rotations: []
      sizes: []
    - !Item
      colors: []
      name: GoodGoal
      positions:
      - !Vector3
        x: 3
        y: 0
        z: 19
      rotations: []
      sizes: []
    t: 250
