!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      - !RGB
        b: 153
        g: 153
        r: 153
      - !RGB
        b: 153
        g: 153
        r: 153
      - !RGB
        b: 153
        g: 153
        r: 153
      - !RGB
        b: 153
        g: 153
        r: 153
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 10
        y: 0
        z: 10
      - !Vector3
        x: 30
        y: 0
        z: 10
      - !Vector3
        x: 5.0
        y: 0
        z: 30
      - !Vector3
        x: 35.0
        y: 0
        z: 30
      - !Vector3
        x: 15.0
        y: 0
        z: 30
      - !Vector3
        x: 25.0
        y: 0
        z: 30
      rotations:
      - 0
      - 0
      - 333.434948822922
      - 26.56505117707799
      - 333.434948822922
      - 26.56505117707799
      sizes:
      - !Vector3
        x: 0.1
        y: 5
        z: 20
      - !Vector3
        x: 0.1
        y: 5
        z: 20
      - !Vector3
        x: 0.1
        y: 5
        z: 21.9606797749979
      - !Vector3
        x: 0.1
        y: 5
        z: 21.9606797749979
      - !Vector3
        x: 0.1
        y: 5
        z: 21.9606797749979
      - !Vector3
        x: 0.1
        y: 5
        z: 21.9606797749979
    - !Item
      colors: []
      name: GoodGoal
      positions:
      - !Vector3
        x: 30.0
        y: 0
        z: 30
      rotations: []
      sizes: []
    - !Item
      colors: []
      name: BadGoal
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 30
      rotations: []
      sizes: []
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 5
      rotations: []
      sizes: []
    t: 250
