!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: Wall
      rotations: [333, 333, 27, 27, 0, 0]
      positions:
      - !Vector3 {x: 5, y: 0, z: 30}
      - !Vector3 {x: 15, y: 0, z: 30}
      - !Vector3 {x: 35, y: 0, z: 30}
      - !Vector3 {x: 25, y: 0, z: 30}
      - !Vector3 {x: 30, y: 0, z: 10}
      - !Vector3 {x: 10, y: 0, z: 10}
      sizes:
      - !Vector3 {x: .1, y: 5, z: 21.8}
      - !Vector3 {x: .1, y: 5, z: 21.8}
      - !Vector3 {x: .1, y: 5, z: 21.8}
      - !Vector3 {x: .1, y: 5, z: 21.8}
      - !Vector3 {x: .1, y: 5, z: 20}
      - !Vector3 {x: .1, y: 5, z: 20}
      colors:
      - !RGB {r: 153, g: 153, b: 153 }
      - !RGB {r: 153, g: 153, b: 153 }
      - !RGB {r: 153, g: 153, b: 153 }
      - !RGB {r: 153, g: 153, b: 153 }
      - !RGB {r: 153, g: 153, b: 153 }
      - !RGB {r: 153, g: 153, b: 153 }
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 10, y: 0, z: 30}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 30, y: 0, z: 30}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 5}
      rotations: [0]
    