!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: 20.5, y: 0.0, z: 20.5}
      rotations: [0]
    - !Item
        name: GoodGoal
        positions:
        - !Vector3 {x: 30.5, y: 0.0, z: 22.5}
        - !Vector3 {x: 22.5, y: 1.0, z: 22.5}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
        - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Cardbox1
      rotations: [0]
      positions:
        - !Vector3 {x: 22.5, y: 0.0, z: 22.5}
      sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
